sudo: required

dist: focal

language: ruby

before_install:
  - nvm install 14

before_script:
- npm install -g stylelint

rvm:
- 2.4
- 2.5
- 2.6
- 2.7

after_success:
- bundle exec codeclimate-test-reporter
